// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Database.proto

package Database

import (
	Req "github.com/DEEBBLUE/MailProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Database_proto protoreflect.FileDescriptor

const file_Database_proto_rawDesc = "" +
	"\n" +
	"\x0eDatabase.proto\x12\bdatabase\x1a\tReq.proto2\xe7\x03\n" +
	"\bDatabase\x121\n" +
	"\n" +
	"CreateUser\x12\x12.req.CreateUserReq\x1a\x0f.req.DefaultRes\x127\n" +
	"\vRepeateUser\x12\x13.req.RepeateUserReq\x1a\x13.req.RepeateUserRes\x121\n" +
	"\n" +
	"DeleteUser\x12\x12.req.DeleteUserReq\x1a\x0f.req.DefaultRes\x12A\n" +
	"\x12UpdateUserPassword\x12\x1a.req.UpdateUserPasswordReq\x1a\x0f.req.DefaultRes\x129\n" +
	"\x0eUpdateUserName\x12\x16.req.UpdateUserNameReq\x1a\x0f.req.DefaultRes\x12C\n" +
	"\x0fRepeateMessages\x12\x17.req.RepeateMessagesReq\x1a\x17.req.RepeateMessagesRes\x127\n" +
	"\rCreateMessage\x12\x15.req.CreateMessageReq\x1a\x0f.req.DefaultRes\x12@\n" +
	"\x0eRepeateMessage\x12\x16.req.RepeateMessageReq\x1a\x16.req.RepeateMessageResB-Z+github.com/DEEBBLUE/MailProtos/api/Databaseb\x06proto3"

var file_Database_proto_goTypes = []any{
	(*Req.CreateUserReq)(nil),         // 0: req.CreateUserReq
	(*Req.RepeateUserReq)(nil),        // 1: req.RepeateUserReq
	(*Req.DeleteUserReq)(nil),         // 2: req.DeleteUserReq
	(*Req.UpdateUserPasswordReq)(nil), // 3: req.UpdateUserPasswordReq
	(*Req.UpdateUserNameReq)(nil),     // 4: req.UpdateUserNameReq
	(*Req.RepeateMessagesReq)(nil),    // 5: req.RepeateMessagesReq
	(*Req.CreateMessageReq)(nil),      // 6: req.CreateMessageReq
	(*Req.RepeateMessageReq)(nil),     // 7: req.RepeateMessageReq
	(*Req.DefaultRes)(nil),            // 8: req.DefaultRes
	(*Req.RepeateUserRes)(nil),        // 9: req.RepeateUserRes
	(*Req.RepeateMessagesRes)(nil),    // 10: req.RepeateMessagesRes
	(*Req.RepeateMessageRes)(nil),     // 11: req.RepeateMessageRes
}
var file_Database_proto_depIdxs = []int32{
	0,  // 0: database.Database.CreateUser:input_type -> req.CreateUserReq
	1,  // 1: database.Database.RepeateUser:input_type -> req.RepeateUserReq
	2,  // 2: database.Database.DeleteUser:input_type -> req.DeleteUserReq
	3,  // 3: database.Database.UpdateUserPassword:input_type -> req.UpdateUserPasswordReq
	4,  // 4: database.Database.UpdateUserName:input_type -> req.UpdateUserNameReq
	5,  // 5: database.Database.RepeateMessages:input_type -> req.RepeateMessagesReq
	6,  // 6: database.Database.CreateMessage:input_type -> req.CreateMessageReq
	7,  // 7: database.Database.RepeateMessage:input_type -> req.RepeateMessageReq
	8,  // 8: database.Database.CreateUser:output_type -> req.DefaultRes
	9,  // 9: database.Database.RepeateUser:output_type -> req.RepeateUserRes
	8,  // 10: database.Database.DeleteUser:output_type -> req.DefaultRes
	8,  // 11: database.Database.UpdateUserPassword:output_type -> req.DefaultRes
	8,  // 12: database.Database.UpdateUserName:output_type -> req.DefaultRes
	10, // 13: database.Database.RepeateMessages:output_type -> req.RepeateMessagesRes
	8,  // 14: database.Database.CreateMessage:output_type -> req.DefaultRes
	11, // 15: database.Database.RepeateMessage:output_type -> req.RepeateMessageRes
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_Database_proto_init() }
func file_Database_proto_init() {
	if File_Database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Database_proto_rawDesc), len(file_Database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Database_proto_goTypes,
		DependencyIndexes: file_Database_proto_depIdxs,
	}.Build()
	File_Database_proto = out.File
	file_Database_proto_goTypes = nil
	file_Database_proto_depIdxs = nil
}
