// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Req.proto

package Req

import (
	Types "github.com/DEEBBLUE/MailProtos/api/Types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultRes) Reset() {
	*x = DefaultRes{}
	mi := &file_Req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRes) ProtoMessage() {}

func (x *DefaultRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRes.ProtoReflect.Descriptor instead.
func (*DefaultRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pass          string                 `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_Req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type RepeateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeateUserReq) Reset() {
	*x = RepeateUserReq{}
	mi := &file_Req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeateUserReq) ProtoMessage() {}

func (x *RepeateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeateUserReq.ProtoReflect.Descriptor instead.
func (*RepeateUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{2}
}

func (x *RepeateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RepeateUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *Types.User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeateUserRes) Reset() {
	*x = RepeateUserRes{}
	mi := &file_Req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeateUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeateUserRes) ProtoMessage() {}

func (x *RepeateUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeateUserRes.ProtoReflect.Descriptor instead.
func (*RepeateUserRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{3}
}

func (x *RepeateUserRes) GetUser() *Types.User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_Req_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateUserPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordReq) Reset() {
	*x = UpdateUserPasswordReq{}
	mi := &file_Req_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordReq) ProtoMessage() {}

func (x *UpdateUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordReq.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdateUserNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewUserName   string                 `protobuf:"bytes,2,opt,name=new_user_name,json=newUserName,proto3" json:"new_user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserNameReq) Reset() {
	*x = UpdateUserNameReq{}
	mi := &file_Req_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNameReq) ProtoMessage() {}

func (x *UpdateUserNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNameReq.ProtoReflect.Descriptor instead.
func (*UpdateUserNameReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserNameReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserNameReq) GetNewUserName() string {
	if x != nil {
		return x.NewUserName
	}
	return ""
}

var File_Req_proto protoreflect.FileDescriptor

const file_Req_proto_rawDesc = "" +
	"\n" +
	"\tReq.proto\x12\x03req\x1a\vTypes.proto\"$\n" +
	"\n" +
	"DefaultRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"9\n" +
	"\rCreateUserReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04pass\x18\x02 \x01(\tR\x04pass\"&\n" +
	"\x0eRepeateUserReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"1\n" +
	"\x0eRepeateUserRes\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.types.UserR\x04user\"%\n" +
	"\rDeleteUserReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"P\n" +
	"\x15UpdateUserPasswordReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"M\n" +
	"\x11UpdateUserNameReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\"\n" +
	"\rnew_user_name\x18\x02 \x01(\tR\vnewUserNameB(Z&github.com/DEEBBLUE/MailProtos/api/Reqb\x06proto3"

var (
	file_Req_proto_rawDescOnce sync.Once
	file_Req_proto_rawDescData []byte
)

func file_Req_proto_rawDescGZIP() []byte {
	file_Req_proto_rawDescOnce.Do(func() {
		file_Req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Req_proto_rawDesc), len(file_Req_proto_rawDesc)))
	})
	return file_Req_proto_rawDescData
}

var file_Req_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Req_proto_goTypes = []any{
	(*DefaultRes)(nil),            // 0: req.DefaultRes
	(*CreateUserReq)(nil),         // 1: req.CreateUserReq
	(*RepeateUserReq)(nil),        // 2: req.RepeateUserReq
	(*RepeateUserRes)(nil),        // 3: req.RepeateUserRes
	(*DeleteUserReq)(nil),         // 4: req.DeleteUserReq
	(*UpdateUserPasswordReq)(nil), // 5: req.UpdateUserPasswordReq
	(*UpdateUserNameReq)(nil),     // 6: req.UpdateUserNameReq
	(*Types.User)(nil),            // 7: types.User
}
var file_Req_proto_depIdxs = []int32{
	7, // 0: req.RepeateUserRes.user:type_name -> types.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Req_proto_init() }
func file_Req_proto_init() {
	if File_Req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Req_proto_rawDesc), len(file_Req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Req_proto_goTypes,
		DependencyIndexes: file_Req_proto_depIdxs,
		MessageInfos:      file_Req_proto_msgTypes,
	}.Build()
	File_Req_proto = out.File
	file_Req_proto_goTypes = nil
	file_Req_proto_depIdxs = nil
}
